apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: nagp
data:
  postgres.conf: |
    listen_addresses = '*'
  POSTGRES_INITDB_ARGS: "--data-checksums"
  PGDATA: /var/lib/postgresql/data/pgdata
  POSTGRES_DB: users
  POSTGRES_USER: postgres
  POSTGRES_CONFIG_FILE: /etc/postgresql/postgresql.conf