apiVersion: v1
kind: Service
metadata:
  name: user-manager-api-service
  namespace: nagp
spec:
  type: LoadBalancer
  selector:
    app: user-manager-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
