# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./UserManagement
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./UserManagement
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./UserManagement
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push docker Image
      uses: docker/build-push-action@v2
      with:
          context: UserManagement
          push: true
          tags: dubeyraj/usermanager
          file: ./UserManagement/Dockerfile
